# .travis.yml
#
# Setup for travis-cl.com
#
# @category  None
# @package   \
# @author    Rick Morice <rick@floor9design.com>
# @copyright Floor9design Ltd
# @license   MIT
# @link      https://github.com/floor9design-ltd/laravel-uuid-model-support
# @version   0.0
# @since     0.0
os: linux
language: php
jobs:
  include:
    - dist: jammy
      php:
        - '8.3.0'

      addons:
        apt:
          update: true
          packages:
            - libonig-dev

      before_script:
        - travis_retry composer self-update
        - travis_retry composer install --no-interaction

      script:
        #- XDEBUG_MODE=coverage ./vendor/phpunit/phpunit/phpunit --coverage-text --coverage-clover=coverage.clover
        #- ./vendor/bin/phpstan

      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - dist: jammy
      php:
        - '8.2.0'

      addons:
        apt:
          update: true
          packages:
            - libonig-dev

      before_script:
        - travis_retry composer self-update
        - travis_retry composer install --no-interaction

      script:
        #- XDEBUG_MODE=coverage ./vendor/phpunit/phpunit/phpunit --coverage-text --coverage-clover=coverage.clover
        #- ./vendor/bin/phpstan

      after_success:
        - bash <(curl -s https://codecov.io/bash)
